"""added extrainfo gin index

Revision ID: a0ee59b29e23
Revises: ef59f09cd67c
Create Date: 2025-01-11 20:46:36.425088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ee59b29e23'
down_revision: Union[str, None] = 'ef59f09cd67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_laptop_extra_info', 'laptop', ['extra_info'], unique=False, postgresql_using='gin', postgresql_ops={'extra_info': 'jsonb_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_laptop_extra_info', table_name='laptop', postgresql_using='gin', postgresql_ops={'extra_info': 'jsonb_ops'})
    # ### end Alembic commands ###
