"""added extrainfo to laptop

Revision ID: ef59f09cd67c
Revises: ccf25f1f32a7
Create Date: 2025-01-11 20:45:06.079436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef59f09cd67c'
down_revision: Union[str, None] = 'ccf25f1f32a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptop', sa.Column('extra_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laptop', 'extra_info')
    # ### end Alembic commands ###
